version: 0.2

phases:
  install:
    commands:
      - "echo Entered the install phase..."
      - "apt-get update -y"
      - "apt-get install -y maven"
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region ${region} --no-include-email)
      - REPOSITORY_URI=${repository_url}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - mvn clean verify
      - docker build -t $REPOSITORY_URI:latest . ${build_options}
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"${container_name}","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
  discard-paths: yes
